name: voices_of_turkey
description: "Türkiyedeki tarihi eserlerin takibini yapabileceğimiz ve açıklamalarını sesli mesaj şeklinde dinleyebileceğimiz bir proje"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.1
  shared_preferences: ^2.0.12
  reactive_forms: ^14.0.0
  google_maps_flutter: ^2.9.0
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
