name: voices_of_turkey
description: "Türkiyedeki tarihi eserlerin takibini yapabileceğimiz ve açıklamalarını sesli mesaj şeklinde dinleyebileceğimiz bir proje"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.1
  shared_preferences: ^2.0.12
  reactive_forms: ^14.0.0
  google_maps_flutter: ^2.9.0
  change_app_package_name: ^1.4.0
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core : ^3.8.0
  flutter_cache_manager: ^3.4.1
  flutter_barcode_scanner: 2.0.0
  flutter_tts: ^4.2.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - assets/json/
